# Use, modification, and distribution are
# subject to the Boost Software License, Version 1.0. (See accompanying
# file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)
#
# Copyright Rene Rivera 2015-2016.

branches:
  only:
    - master
    - develop

sudo: required

language: c

compiler:
  - gcc

git:
  # We avoid fetching submodules so that we can set the EOL
  # style to fetch them as needed.
  submodules: false

addons:
  apt:
    packages:
      - p7zip-full
      - docutils-common
      - docutils-doc
      - docbook
      - docbook-xml
      - docbook-xsl
      - xsltproc
      - doxygen
      - dvipsk-ja
      - texlive

env:
  global:
    - secure: "DC12OV65iyBzELywj19yI4S8DmmBmZO8hbT3Iq0kJ4yo0aMQzzJDsVpmm2Jwk/Qf/yLyBsAhkpanScJJ9eEekmK8OZN8H9EJ1kgai58IWk0gWKKzJ0lyQH/vsYEyfxCSwqejoIdd07nQh5B/1L5Th3I2vLT2udHUPU2Np/MKgUw="
  matrix:
    - TRAVIS_EMPTY_JOB_WORKAROUND=true

matrix:
  exclude:
    - env: TRAVIS_EMPTY_JOB_WORKAROUND=true
  include:
    # Simple integrated status tests check.
    - env: STATUS_TESTS=true
    
    # Build release package for LF end-of-line style text files.
    - env: RELEASE_BUILD=LF
    
    # Build release package for CRLF end-of-line style text files (i.e. for Windows).
    - env: RELEASE_BUILD=CRLF

before_install:
  # Fetch the script to do the actual building/testing.
  - |
    if [[ "${STATUS_TESTS}" == "true" ]]; then
      wget "https://raw.githubusercontent.com/boostorg/release-tools/develop/ci_boost_status.py" -O ../script.py
    fi
  - |
    if [[ "${RELEASE_BUILD}" == "LF" || "${RELEASE_BUILD}" == "CRLF" ]]; then
      wget "https://raw.githubusercontent.com/boostorg/release-tools/develop/ci_boost_release.py" -O ../script.py
    fi

install: python "${TRAVIS_BUILD_DIR}/../script.py" install
before_script: python "${TRAVIS_BUILD_DIR}/../script.py" before_script
script: python "${TRAVIS_BUILD_DIR}/../script.py" script
after_success: python "${TRAVIS_BUILD_DIR}/../script.py" after_success
after_failure: python "${TRAVIS_BUILD_DIR}/../script.py" after_failure
after_script: python "${TRAVIS_BUILD_DIR}/../script.py" after_script
